version: "3.7"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile-start-api
    init: true
    networks:
      - todo-app-backend
    environment:
      - MONGO_URI=mongodb://mongo/todo-app
      - JWT_SECRET=EbghPGqURlGkhnHIjO4EJwVOC+jenZN/dawAidUCt7g7PeWg4TrrfEhJtZBm0hjRe2i7R9K7YKZ+2N4M+OmtI/3Or31NtFiI/izgAt4oZ6w7Cos+xN8AzA0OyEDuihLE/YGtKSB9BWvxvA2OECYv2DOqozGOX3zKvZ3IT45N0zB5NcFFWXb4mkK/hJ/lH8x/Llfq6LfOo4Z9jIL/UuRYXtTIjvI4qDgH+PVZ56CCSLHmCe7WxUzwHhQS4oOdDzDp0mEo5iKpa9xFWtbAozoiPlrp3YhB3sDScD8tDznM/lSkOHfBMUe5s7WSwzxTAVkDiJZsUX5W4eIfoRCWamYIOQ==
    ports:
      - "4000:4000"

  mongo:
    image: mongo
    restart: always
    networks:
      - todo-app-backend

networks:
  todo-app-backend:
